Add unit tests for cpdFindChangePoint function
Cambridge-ICCS/ONEFlux pull request #57
Opened 2024-11-28 11:06 UTC by tztsai

## Summary
This pull request extends the unit tests for the cpdFindChangePoint MATLAB function. The new tests cover additional scenarios to ensure the robustness and correctness of the function under various conditions.

## Changes Made
- Extended Test Cases:
  - Added tests for scenarios with no change points.
  - Added tests for change points at the start and end of the data.
  - Added tests for data with noise.
  - Added tests for invalid inputs and insufficient data.
- Test Files Modified:
  - test_cpdFindChangePoint20100901.py: Extended with new test cases to cover more edge cases and scenarios.#
 
## Detailed Description
- No Change Points: Added a test to verify the function's behavior when there are no change points in the data.
- Change Points at Start/End: Added tests to check if the function correctly identifies change points located at the start or end of the data series.
- Data with Noise: Added a test to ensure the function can still identify change points when the data contains noise.
- Invalid Inputs: Added tests to handle scenarios with invalid inputs, such as empty arrays or insufficient data points.

2024-11-28 14:41 UTC, dorchard commented
Reviewing in progress. Could we get a quick summary of what `cpdFindChangePoint` does to help assess the tests? This could also be added to the MATLAB code so we have extra documentation.

2024-11-28 14:42 UTC, dorchard commented
@isaacaka has some documentation too that can be included.

2024-12-02 11:03 UTC, j-emberton commented
Hi @tztsai,

I've updated the branch we are merging into from `main` to `ustar_cp_refactor_main`. Because of this there now seems to be a conflict between the `tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py` files.

I've also tried to run the tests locally but get the following error:
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/179ecb6b-69c2-40d2-bd6a-2c800e782f16">

I'll take a look at the tests separately just now but won't be able to run them.

2024-12-02 14:38 UTC, tztsai commented
> Hi @tztsai,
> 
> I've updated the branch we are merging into from `main` to `ustar_cp_refactor_main`. Because of this there now seems to be a conflict between the `tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py` files.
> 
> I've also tried to run the tests locally but get the following error: <img alt="image" width="1113" src="https://private-user-images.githubusercontent.com/60827102/391516727-179ecb6b-69c2-40d2-bd6a-2c800e782f16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTAzOTksIm5iZiI6MTczMzE1MDA5OSwicGF0aCI6Ii82MDgyNzEwMi8zOTE1MTY3MjctMTc5ZWNiNmItNjljMi00MGQyLWJkNmEtMmM4MDBlNzgyZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE0MzQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YWQxY2FlYjM1MzFhNjVjYjg3NDFlN2E5NzE1NTIzMjY3NjBjNmU5MDU3NGJhZmFlMGZmMjY5ZDQ5NzM2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DsW9DF0ls8hIdthrxz_CZ9Nqx4FYt6yMMePUW_HrLPE">
> 
> I'll take a look at the tests separately just now but won't be able to run them.

It seems due to a conflict between `ustar_cp_refactor_main` and `main`, not related to the update here. Perhaps `context.py` should be removed from `ustar_cp_refactor_main`.

2024-12-03 09:25 UTC, j-emberton commented
I don't think you have branched off of ustar_cp_refactor_main, therefore the rest of the code in your branch isn't up to date and you don't have access to all the code that we've developed to date. You should rebase your branch and make sure the tests work before requesting a review.

2024-12-03 09:26 UTC, j-emberton requested changes
This code isn't ready for review. Please fix and resubmit.

2024-12-03 14:30 UTC, casterkay commented
I've rebased to the head of `ustar_cp_refactor_main` now.

2024-12-04 19:18 UTC, j-emberton requested changes, later dismissed
Not all tests pass when I run locally. This PR isn't ready for review.

2024-12-06 10:43 UTC, dorchard commented
I can confirm that I've got tests failing too. It looks like a problem with the rebase:
```
============================================================== short test summary info ===============================================================
FAILED tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py::test_cpdFindChangePoint_no_change - AssertionError: Cp2 should be NaN when there's no change point
FAILED tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py::test_cpdFindChangePoint_change_at_start - AssertionError: Cp2 should be near the start
FAILED tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py::test_cpdFindChangePoint_change_at_end - AssertionError: Cp2 should be near the end
FAILED tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py::test_cpdFindChangePoint_with_noise - AssertionError: Cp2 should be near 5 despite noise
FAILED tests/unit_tests/test_ustar_cp/test_rounding.py::test_round - assert 3 == 2
====================================================== 5 failed, 16 passed in 74.17s (0:01:14) =======================================================
```

2024-12-06 15:45 UTC, j-emberton commented
This PR is now up to date with `ustar_cp_refactor_main` and includes Issacs fix from #61 .

4 tests associated with the specific `cpdFindChangePoint` function now fail but all others pass

2024-12-13 16:18 UTC, dorchard commented
Could do with some site-based data tests.

2025-01-30 16:09 UTC, dorchard approved these changes

2025-01-30 18:27 UTC, j-emberton commented on tests/conftest.py
> +#'to_python' needs to be added back in
Can we remove these old comments

2025-01-30 18:32 UTC, j-emberton commented on tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py
> +    # x = 1.1111111111111111111
I think these comments can be deleted now

2025-01-30 18:35 UTC, j-emberton commented on tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py
> +    # print(expected_x[:10].shape, expected_y[:10].shape)
I think these comments can be deleted

2025-01-30 18:37 UTC, j-emberton commented on tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py
> +## TODO: Add site data tests for computeReducedModels
To do?

2025-01-30 18:40 UTC, j-emberton commented on tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py
> +    #print(output_data['Fc3'])
These comments can be deleted

2025-01-30 18:43 UTC, j-emberton commented
Good work.

I think there's just a few out of date comments that can be deleted to tidy up then this is ready for merging.

2025-01-31 12:28 UTC, isaacaka commented on tests/unit_tests/test_ustar_cp/test_cpdFindChangePoint20100901.py
> +## TODO: Add site data tests for computeReducedModels
Yes, added that thanks.

2025-01-31 12:31 UTC, merged